services:
  api:
    build: ./api
    ports:
      - 127.0.0.1:80:3000
    env_file: .env
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    restart: unless-stopped
    command: npm start

  worker:
    build: ./worker
    # ports:
    #   - 127.0.0.1:3000:3000
    env_file: .env
    volumes:
      - ./worker:/app
      - node_modules_worker:/app/node_modules
    restart: unless-stopped
    command: npm start
    deploy:
      replicas: 5
volumes:
  node_modules_api:
  node_modules_worker:
