services:
  api:
    build: .
    ports:
      - 80:3000
      - 3030:3030
    env_file: .env
    volumes:
      - .:/app
      - node_modules_api:/app/node_modules
    restart: unless-stopped
    networks:
      - llm
    command: npm start
  mysql:
    image: mysql:8.2
    restart: unless-stopped
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
        - 3306:3306
    volumes:
        - mysql:/var/lib/mysql
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        - .:/app
    networks:
        - llm
volumes:
  node_modules_api:
  mysql:
networks:
  llm:
    name: llm
